language: ruby
rvm:
 - 2.3.1
services:
  - postgresql
addons:
    code_climate:
        repo_token: da6a21eb0dc0f0019d5b00f3ff455b34b7bc51882348f3414186b5f6600851fe
before_script:
  - psql -c 'create database dummy_test;' -U postgres
  - sudo apt-get install libqt4-dev libqtwebkit-dev
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
